# For AWS Stage EKS, we increase replicas, limit scaling, and enhance security settings.

# normally this would be higher but not for this POC single replca service
replicaCount: 3

image:
  repository: mayth/simple-upload-server 
  #tag: stage-latest
  tag: b0e711dcdfe9be60ed20ef5447a20dbd42f467c7f16772c0581241f9e82ea9ec

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: alb
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
  hosts:
    - host: stage.widgetapi.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - stage.widgetapi.example.com
      secretName: stage-wildcard-cert

resources:
  requests:
    cpu: "1"
    memory: "2Gi"
  limits:
    cpu: "2"
    memory: "4Gi"

persistence:
  enabled: true
  storageClass: gp2
  size: 20Gi

# secrets must be created in the same namespace as the deployment like this
#kubectl create secret generic db-credentials \
#  --namespace widgetapi-stage \
#  --from-literal=DATABASE_URL="postgres://user:pass@prod-db.widgetapi.example.com:5432/widgetapi"
env:
  LOG_LEVEL: "error"
  DATABASE_URL:
    secretKeyRef:
      name: db-credentials
      key: DATABASE_URL

environment:
  TOKEN: "sometoken"  # Ensure consistency in naming across templates
  UPLOAD_LIMIT: "300MB"
