apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: widgetapi-policy
spec:
  podSelector:
    matchLabels:
      app: widgetapi
  policyTypes:
    - Ingress
  ingress:
    - from: []
      ports:
        - protocol: TCP
          port: 8080
