apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: widgetapi-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: widgetapi
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
