apiVersion: v1
kind: Secret
metadata:
  name: widgetapi-secrets
type: Opaque
data:
  TOKEN: {{ .Values.environment.TOKEN | default "default-token" | b64enc }}
  UPLOAD_LIMIT: {{ .Values.environment.UPLOAD_LIMIT | default "50MB" | b64enc }}
